# Generated by Django 4.2.10 on 2024-03-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Earth',
        ),
    ]
