# Generated by Django 4.2.10 on 2024-03-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='page_name',
            field=models.CharField(default='air', max_length=255),
        ),
    ]
