# Generated by Django 4.2.11 on 2024-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0006_alter_earth_options_alter_earth_facts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earth',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
